
# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: run npm tests.

on:
  push:
    branches: [run-tests-on-ci]
  pull_request:
    branches: [run-tests-on-ci]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install modules
        run: npm ci
      - name: Run tests
        run: npm test
